# Generated by Django 3.2.9 on 2021-11-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fazenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'ordering': ['endereco']},
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='estado',
            field=models.CharField(max_length=2, verbose_name='estado'),
        ),
    ]
