# Generated by Django 3.2.9 on 2021-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fazenda', '0002_auto_20211119_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fazenda',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='fazenda',
            name='nome',
            field=models.CharField(max_length=100, null=True, verbose_name='nome'),
        ),
    ]
