# Generated by Django 3.2.9 on 2021-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fazenda', '0003_auto_20211119_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fazenda',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
    ]
