# Generated by Django 3.2.9 on 2021-11-19 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producao',
            options={'ordering': ['nome']},
        ),
    ]
