# Generated by Django 3.2.5 on 2022-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0003_alter_producao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='producao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
