# Generated by Django 3.2.5 on 2022-05-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producao', '0004_producao_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data de plantio')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Producao.producao')),
            ],
            options={
                'verbose_name': 'Plantio',
                'verbose_name_plural': 'Plantios',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
